###################################################################

# Created by write_sdc on Sat Aug 13 15:42:01 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max_library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -min_library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c
set_wire_load_model -name tsmc13_wl30 -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports RX_IN_S]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[7]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[6]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {TX_IN_P[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports TX_IN_V]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {Prescale[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {Prescale[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {Prescale[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {Prescale[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {Prescale[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports parity_enable]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports parity_type]
set_load -pin_load 50 [get_ports {RX_OUT_P[7]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[6]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[5]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[4]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[3]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[2]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[1]}]
set_load -pin_load 50 [get_ports {RX_OUT_P[0]}]
set_load -pin_load 50 [get_ports RX_OUT_V]
set_load -pin_load 50 [get_ports TX_OUT_S]
set_load -pin_load 50 [get_ports TX_OUT_V]
create_clock [get_ports TX_CLK]  -name tx_clk  -period 100  -waveform {0 50}
set_clock_latency 0  [get_clocks tx_clk]
set_clock_uncertainty -setup 0.25  [get_clocks tx_clk]
set_clock_uncertainty -hold 0.05  [get_clocks tx_clk]
set_clock_transition -max -rise 0.1 [get_clocks tx_clk]
set_clock_transition -min -rise 0.1 [get_clocks tx_clk]
set_clock_transition -max -fall 0.1 [get_clocks tx_clk]
set_clock_transition -min -fall 0.1 [get_clocks tx_clk]
create_clock [get_ports RX_CLK]  -name rx_clk  -period 12  -waveform {0 6}
set_clock_latency 0  [get_clocks rx_clk]
set_clock_uncertainty -setup 0.25  [get_clocks rx_clk]
set_clock_uncertainty -hold 0.05  [get_clocks rx_clk]
set_clock_transition -max -rise 0.1 [get_clocks rx_clk]
set_clock_transition -min -rise 0.1 [get_clocks rx_clk]
set_clock_transition -max -fall 0.1 [get_clocks rx_clk]
set_clock_transition -min -fall 0.1 [get_clocks rx_clk]
set_input_delay -clock tx_clk  20  [get_ports TX_IN_V]
set_input_delay -clock tx_clk  20  [get_ports parity_enable]
set_input_delay -clock tx_clk  20  [get_ports parity_type]
set_input_delay -clock rx_clk  20  [get_ports RX_IN_S]
set_input_delay -clock rx_clk  20  [get_ports {Prescale[4]}]
set_input_delay -clock rx_clk  20  [get_ports {Prescale[3]}]
set_input_delay -clock rx_clk  20  [get_ports {Prescale[2]}]
set_input_delay -clock rx_clk  20  [get_ports {Prescale[1]}]
set_input_delay -clock rx_clk  20  [get_ports {Prescale[0]}]
set_output_delay -clock tx_clk  2.4  [get_ports TX_OUT_S]
set_output_delay -clock tx_clk  2.4  [get_ports TX_OUT_V]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[7]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[6]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[5]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[4]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[3]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[2]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[1]}]
set_output_delay -clock rx_clk  2.4  [get_ports {RX_OUT_P[0]}]
set_output_delay -clock rx_clk  2.4  [get_ports RX_OUT_V]
